config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  root 'home#index'

  resources :posts do
    collection do
      get 'search'
    end
  end
  
  get 'posts', to: 'posts#index'
  get 'contacts', to: 'contacts#index'
  get 'about', to: 'about#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
     belongs_to :user
     belongs_to :category
     
  validates :title, presence: true
  validates :content, presence: true

  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :posts  
          validates :nickname, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @latest_posts = Post.includes(:user, :category).order(created_at: :desc).limit(3)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    if params[:category].present?
      @category = Category.find(params[:category])
      @posts = @category.posts
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Пост був успішно створений.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Пост був успішно оновлений.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Пост був успішно видалений.'
  end

  def search
    @query = params[:query]
    @posts = Post.where("title LIKE ? OR content LIKE ?", "%#{@query}%", "%#{@query}%")
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end

  def authorize_user!
    unless @post.user == current_user
      redirect_to posts_path, alert: 'Ви не маєте права виконувати цю дію.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<body>
  <div class="container mt-4">
    <h1><%= t('about.title') %></h1>
    <p><%= t('about.content') %></p>
  </div>
</body>

app/views/contacts/index.html.erb
<body>
  <div class="container mt-4">
    <h1><%= t('contacts.title') %></h1>
    <p><%= t('contacts.content') %></p>
  </div>
</body>

app/views/home/index.html.erb
<!-- app/views/pages/home.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <title>Головна сторінка</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
  <div class="jumbotron">
    <h1 class="display-4"><%= t('welcome.title') %></h1>
    <p class="lead"><%= t('welcome.description') %></p>
    <hr class="my-4">
    <p><%= t('welcome.register_now') %></p>
    <%= link_to t('welcome.register_button'), new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  </div>

  <div class="search mb-4">
    <h2><%= t('search.title') %></h2>
    <%= form_with url: search_posts_path, method: :get, local: true do %>
      <div class="form-group">
        <%= text_field_tag :query, params[:query], placeholder: t('search.placeholder'), class: 'form-control' %>
      </div>
      <%= submit_tag t('search.button'), class: 'btn btn-primary' %>
    <% end %>
  </div>

  <div class="about mb-4">
    <h2><%= t('about.title') %></h2>
    <p><%= t('about.description') %></p>
  </div>

  <div class="latest-posts">
    <h2><%= t('latest_posts.title') %></h2>
    <% @latest_posts.each do |post| %>
      <div class="card mb-3">
        <div class="card-body">
          <h3 class="card-title"><%= link_to post.title, post_path(post) %></h3>
          <p class="card-text"><%= truncate(post.content, length: 100) %></p>
          <p class="card-text"><strong><%= t('latest_posts.category') %>:</strong> <%= post.category.name %></p>
          <p class="card-text"><strong><%= t('latest_posts.author') %>:</strong> <%= post.user.nickname %></p>
        </div>
      </div>
    <% end %>
  </div>

  

</body>

</html>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <title>GameForum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to t('navbar.brand'), root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to t('navbar.home'), root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('navbar.posts'), posts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('navbar.contacts'), contacts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('navbar.about'), about_path, class: 'nav-link' %>
          </li>
        </ul>
        <%= form_with url: search_posts_path, method: :get, local: true, class: 'form-inline my-2 my-lg-0' do %>
          <input class="form-control mr-sm-2" type="search" placeholder="<%= t('navbar.search_placeholder') %>" aria-label="Search" name="query">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= t('navbar.search_button') %></button>
        <% end %>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to t('navbar.sign_up'), new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to t('navbar.sign_in'), new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "English", url_for(locale: 'en'), class: (I18n.locale == :en ? 'nav-link active' : 'nav-link') %>
          </li>
          <li class="nav-item">
            <%= link_to "Українська", url_for(locale: 'uk'), class: (I18n.locale == :uk ? 'nav-link active' : 'nav-link') %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <%= yield %>
  </div>
</body>

</html>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Post</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  </head>
<body>
  <div class="container mt-4">
    <h1><%= t('posts.edit.title') %></h1>

    <%= form_with(model: @post, local: true) do |form| %>
      <% if @post.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@post.errors.count, t('posts.edit.error_prohibited')) %> <%= t('posts.edit.error_prohibited') %>:</h2>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :title, t('posts.edit.title_label') %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :content, t('posts.edit.content_label') %>
        <%= form.text_area :content, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit t('posts.edit.update_button'), class: 'btn btn-secondary' %>
      </div>
    <% end %>

    <%= link_to t('posts.edit.back'), posts_path, class: 'btn btn-secondary' %>
  </div>
</body>


</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Пости</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <body>
  <div class="container mt-4">
    <h1><%= t('posts.index.title') %></h1>

    <% if user_signed_in? %>
      <%= link_to t('posts.index.add_post'), new_post_path, class: 'btn btn-primary mb-4' %>
    <% end %>

    <div class="filter mb-4">
      <%= form_with url: posts_path, method: :get, local: true, class: 'form-inline' do %>
        <div class="form-group mr-2">
          <%= select_tag :category, options_from_collection_for_select(@categories, :id, :name, params[:category]), include_blank: t('posts.index.all_categories'), class: 'form-control' %>
        </div>
        <%= submit_tag t('posts.index.filter_button'), class: 'btn btn-secondary' %>
      <% end %>
    </div>

    <div class="posts-container">
      <% @posts.each do |post| %>
        <div class="card mb-3">
          <div class="card-body">
            <h2 class="card-title"><%= link_to post.title, post_path(post) %></h2>
            <p class="card-text"><%= truncate(post.content, length: 100) %></p>
            <p class="card-text"><strong><%= t('posts.index.category') %>:</strong> <%= post.category.name %></p>
            <p class="card-text"><strong><%= t('posts.index.author') %>:</strong> <%= post.user.nickname %></p>
            <%= link_to t('posts.index.view'), post, class: 'btn btn-info mr-2' %>
            <% if post.user == current_user %>
              <%= link_to t('posts.index.edit'), edit_post_path(post), class: 'btn btn-warning mr-2' %>
              <%= link_to t('posts.index.delete'), post, method: :delete, data: { confirm: t('posts.index.confirm_delete') }, class: 'btn btn-danger' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</body>



</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Post</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <div class="container mt-4">
    <h1><%= t('posts.new.title') %></h1>
    <%= form_with(model: @post, local: true, class: 'form') do |form| %>
      <% if @post.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@post.errors.count, t('posts.new.error')) %> <%= t('posts.new.prohibited') %>:</h2>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title, t('posts.new.title_label') %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
fdsgdfgsdf
      <div class="form-group">
        <%= form.label :content, t('posts.new.content_label') %>
        <%= form.text_area :content, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :category_id, t('posts.new.category') %>
        <%= form.collection_select :category_id, Category.all, :id, :name, prompt: t('posts.new.select_category'), class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit t('posts.new.create_post'), class: 'btn btn-primary' %>
      </div>
    <% end %>
    <%= link_to t('posts.new.back'), posts_path, class: 'btn btn-secondary mt-3' %>
  </div>
</body>



</html>

app/views/posts/search.html.erb
<!-- app/views/posts/search.html.erb -->
<h1>Результати пошуку</h1>

<% if @posts.any? %>
  <% @posts.each do |post| %>
    <div class="post">
      <h3><%= link_to post.title, post %></h3>
      <p><%= truncate(post.content, length: 150) %></p>
      <p><strong>Категорія:</strong> <%= post.category.name %></p>
      <p><strong>Автор:</strong> <%= post.user.nickname %> | <%= post.created_at.strftime("%B %d, %Y") %></p>
    </div>
  <% end %>
<% else %>
  <p>No posts found for your search query.</p>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('posts.show.title_label') %>:</strong>
  <%= @post.title %>
</p>

<p>
  <strong><%= t('posts.show.content_label') %>:</strong>
  <%= @post.content %>
</p>

<p>
  <strong><%= t('posts.show.category_label') %>:</strong>
  <%= @post.category.name %>
</p>

<% if @post.user == current_user %>
  <%= link_to t('posts.show.edit'), edit_post_path(@post) %> |
  <%= link_to t('posts.show.destroy'), @post, method: :delete, data: { confirm: t('posts.show.confirm_delete') } %> |
<% end %>

<%= link_to t('posts.show.back'), posts_path %>